# Generated by Django 4.2.6 on 2023-11-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_team_team_members_invites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invites',
            name='team_id',
            field=models.IntegerField(),
        ),
    ]
