# Generated by Django 4.2.6 on 2023-11-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_invites_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_members',
            name='team_id',
            field=models.IntegerField(),
        ),
    ]
