# Generated by Django 4.2.6 on 2023-11-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_team_members_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invites',
            name='invite_status',
            field=models.CharField(choices=[('S', 'Sent'), ('R', 'Rejected'), ('A', 'Accepted')], default='S', max_length=1),
        ),
    ]
