# Generated by Django 4.2.6 on 2023-11-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_assigned_to_alter_task_created_by'),
        ('tasks', '0006_alter_invites_invite_status_and_more'),
    ]

    operations = [
    ]
