# Generated by Django 4.2.6 on 2023-11-22 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_invites_invite_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_members',
            field=models.ManyToManyField(related_name='team_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
