# Generated by Django 4.2.6 on 2023-11-22 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_team_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_members',
        ),
        migrations.AddField(
            model_name='team_members',
            name='member_of_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.team'),
        ),
        migrations.AlterField(
            model_name='invites',
            name='invite_status',
            field=models.CharField(choices=[('S', 'Sent'), ('R', 'Rejected'), ('A', 'Accepted')], default='S', max_length=1),
        ),
    ]
