# Generated by Django 4.2.6 on 2023-11-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_remove_team_team_members_team_members_member_of_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invites',
            name='invite_status',
            field=models.CharField(choices=[('R', 'Rejected'), ('S', 'Sent'), ('A', 'Accepted')], default='S', max_length=1),
        ),
    ]
