# Generated by Django 4.2.6 on 2023-11-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_task_related_to_team_alter_invites_invite_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invites',
            name='invite_status',
            field=models.CharField(choices=[('R', 'Rejected'), ('S', 'Sent'), ('A', 'Accepted')], default='S', max_length=1),
        ),
    ]
