# Generated by Django 4.2.6 on 2023-11-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_team_team_member_alter_invites_invite_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_member',
        ),
        migrations.AlterField(
            model_name='invites',
            name='invite_status',
            field=models.CharField(choices=[('S', 'Sent'), ('A', 'Accepted'), ('R', 'Rejected')], default='S', max_length=1),
        ),
    ]
