# Generated by Django 4.2.6 on 2023-11-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_alter_invites_invite_status_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invites',
            name='invite_status',
            field=models.CharField(choices=[('R', 'Rejected'), ('S', 'Sent'), ('A', 'Accepted')], default='S', max_length=1),
        ),
        migrations.DeleteModel(
            name='Team_Members',
        ),
    ]
