# Generated by Django 4.2.6 on 2023-11-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_alter_invites_invite_status_delete_team_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_member',
            new_name='team_members',
        ),
        migrations.AlterField(
            model_name='invites',
            name='invite_status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('S', 'Sent')], default='S', max_length=1),
        ),
    ]
