# Generated by Django 4.2.6 on 2023-11-28 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_alter_invites_invite_status'),
        ('tasks', '0025_rename_team_member_team_team_members_and_more'),
    ]

    operations = [
    ]
