# Generated by Django 4.2.6 on 2023-11-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_alter_invites_invite_status'),
        ('tasks', '0026_merge_20231128_1950'),
    ]

    operations = [
    ]
