# Generated by Django 4.2.6 on 2023-12-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_merge_20231128_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invites',
            name='invite_status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('S', 'Sent')], default='S', max_length=1),
        ),
    ]
