# Generated by Django 4.2.6 on 2023-12-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_alter_invites_invite_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invites',
            name='invite_status',
            field=models.CharField(choices=[('A', 'Accepted'), ('S', 'Sent'), ('R', 'Rejected')], default='S', max_length=1),
        ),
    ]
