# Generated by Django 4.2.6 on 2023-12-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_alter_invites_invite_status'),
        ('tasks', '0028_alter_invites_invite_status'),
    ]

    operations = [
    ]
