# Generated by Django 4.2.6 on 2023-12-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_alter_invites_invite_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invites',
            name='invite_status',
            field=models.CharField(choices=[('S', 'Sent'), ('A', 'Accepted'), ('R', 'Rejected')], default='S', max_length=1),
        ),
    ]
