# Generated by Django 4.2.6 on 2023-12-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_alter_invites_invite_status'),
        ('tasks', '0032_alter_invites_invite_status'),
    ]

    operations = [
    ]
