# Generated by Django 4.2.6 on 2023-12-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_merge_20231207_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invites',
            name='invite_status',
            field=models.CharField(choices=[('R', 'Rejected'), ('S', 'Sent'), ('A', 'Accepted')], default='S', max_length=1),
        ),
    ]
