# Generated by Django 4.2.6 on 2023-12-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_merge_20231206_1511'),
        ('tasks', '0034_alter_invites_invite_status'),
        ('tasks', '0035_alter_task_related_to_team'),
    ]

    operations = [
    ]
