# Generated by Django 4.2.6 on 2023-12-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0037_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('', '-'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True),
        ),
    ]
