# Generated by Django 4.2.6 on 2023-12-11 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0039_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='related_to_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
