# Generated by Django 4.2.6 on 2023-12-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0039_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='changes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='task_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
