# Generated by Django 4.2.6 on 2023-12-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0040_auditlog_related_to_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='related_to_task',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='task_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=100),
        ),
    ]
