# Generated by Django 4.2.6 on 2023-12-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0040_alter_auditlog_changes_alter_auditlog_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('', '-'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
