# Generated by Django 4.2.6 on 2023-12-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0041_remove_auditlog_related_to_task_auditlog_task_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='changes',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
