# Generated by Django 4.2.6 on 2023-12-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0041_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='changes',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
