# Generated by Django 4.2.6 on 2023-12-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0039_alter_task_priority_alter_user_first_name_and_more'),
        ('tasks', '0039_alter_task_status'),
        ('tasks', '0044_alter_task_completed'),
    ]

    operations = [
    ]
