# Generated by Django 4.2.6 on 2023-12-15 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0045_merge_20231214_1348'),
        ('tasks', '0046_remove_task_status_alter_task_completed'),
    ]

    operations = [
    ]
