# Generated by Django 4.2.6 on 2023-12-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0047_merge_20231215_0922'),
        ('tasks', '0047_merge_20231215_1213'),
    ]

    operations = [
    ]
